vioprint("di sebuah caffe terdapat 2 orang bersahabat mengerjakan tugas ngoding bersama")
print("nama orang pertama")
orang1 = input(": ")
print("nama orang kedua")
orang2 = input(": ")
pelatihan1 = input("nama pelatihan: ")
jam1 = input("jam masuk: ")
Tempat = input("tempat: ")

print("========================================")
print(orang1, ": saat pelatihan ngoding itu membahas apa saja", orang2)
print(orang2, ": mempelajari dasar-dasar bahasa python")
print(orang1, ": ohw, ada tugas kah?")
print(orang1, ": ada, tapi tenang tugasnya mudah kok. soalnya masih dasar-dasar.")
print(orang1, ": kita ketemuan yah, buat ngerjain bareng nanti", jam1)
print("=======================================")
print(orang1, ": wahhh, kamu orangnya tepat waktu banget yah. hhehehe, maaf yah aku telat ")

print("Pada suatu hari terdapat dua orang sahabat yang ingin berkumpul di sebuah warung")
print("nama untuk orang pertama")
orang1 = input(": ")
print("nama untuk orang kedua")
orang2 = input(": ")
matkul1 = input("nama matkul : ")
jam1 = input("jam masuk : ")
jam2 = input("jam selesai : ")
l1 = input("lantai kelas pertama berapa? : ")
l2 = input("lantai kelas kedua berapa? : ")

print("==============================================")
print(orang1, ": besok ada matkul apa saja?")
print(orang2, ": matkul untuk besok itu", matkul1)
print(orang1, ": jam berapa emangnya?")
print(orang2, ": untuk", matkul1, jam1)
print(orang1, ": sampai jam brp emang?")
jampertama = int(jam1)
jamkedua = int(jam2)
lantai1 = int(l1)
lantai2 = int(l2)
hasil = jamkedua - jampertama
print(orang2, ": untuk", matkul1, "selesai", jam2)
print(orang1, ": berarti cuma", hasil, "jam")
print(orang2, ": iya, aku nanti di lantai", lantai1)
print(orang1, ": ohh aku di lantai", lantai2)
print(orang2, ": oke")
print("Lantai", orang1, "lebih tinggi dari lantai", orang2, "?")
hasil = lantai1 > lantai2
print(hasil)
print("akhirnya besok mereka berangkat ke kampus bersama")
